////////////////////////////////////////////////////////////////////////////////
///
/// \file buildStamp.hpp
/// --------------------
///
/// Copyright (c) 2026 the SpectrumWorx contributors.
/// SPDX-License-Identifier: GPL-3.0-or-later
///
////////////////////////////////////////////////////////////////////////////////
//------------------------------------------------------------------------------
#ifndef buildStamp_hpp__5B1D6A2E_9C74_43F1_8E0B_2A7F41D9C6B3
#define buildStamp_hpp__5B1D6A2E_9C74_43F1_8E0B_2A7F41D9C6B3

namespace LE::SW
{

////////////////////////////////////////////////////////////////////////////////
///
/// \class BuildStamp
///
/// \brief When this binary was built, and from what.
///
///   Not versionConfiguration.hpp and not sst-plugininfra's VersionInformation,
/// both of which are written at *configure* time: a tree configured in June and
/// rebuilt this morning reports June through either of them. These three strings
/// are regenerated by every build, which is the whole point of them -- they are
/// what the editor draws along its bottom edge so that "am I running the binary
/// I just built" is a question answered by looking rather than by guessing.
///
/// \see src/buildStamp.cmake and cmake/writeBuildStamp.cmake, which is where the
/// definitions come from, and SpectrumWorxEditor::paintBuildStamp().
///
////////////////////////////////////////////////////////////////////////////////

struct BuildStamp
{
    /// Local time, "YYYY-MM-DD" and "HH:MM:SS".
    static char const *const date;
    static char const *const time;

    /// The abbreviated commit, with a trailing '+' if tracked files had been
    /// modified -- so a stamp with no '+' names a tree somebody else can check
    /// out. "no-git" when the source is not a repository.
    static char const *const commit;
}; // struct BuildStamp

} // namespace LE::SW

#endif // buildStamp_hpp
